[general]
import = [
"catppuccin-mocha.toml",
]
live_config_reload = true

[env]

[window]
dimensions = { columns = 101, lines = 24 }
decorations = "Full"

[font]
normal = { family = "JetBrainsMono NFM", style = "Regular"}
bold = { family = "JetBrainsMono NFM", style = "Bold"}
italic = { family = "JetBrainsMono NFM", style = "Italic"}
bold_italic = { family = "JetBrainsMono NFM", style = "Bold Italic"}
size = 24.0
