# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$character$directory$git_branch'
add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[directory]
style = 'bold green'

[git_branch]
format = '[\[](bold green)[$branch(:$remote_branch)]($style)[\]](bold green) '
style = 'bold cyan'
